steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/twilio-df-integration', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/twilio-df-integration']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'twilio-df-integration', '--image', 'gcr.io/${PROJECT_ID}/twilio-df-integration', '--region', 'us-central1', '--port', '8080', '--env-vars-file', 'env.yaml']
images:
- gcr.io/${PROJECT_ID}/twilio-df-integration